title: "securitypuppy"
description: 
baseurl: 
url: "https://securitypuppy.com"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

webmaster_verifications:
  google: Iu_035jUE8GBrL2ldo16TJNC3V-nfiMMQZJCRmoZD6I
  yandex: a73334fea2fcfba5
  bing: 0C8DA626DE53E04C6AF918B5FB85176E

cloudflare_analytics: 48d359443ea64517a458ac8b413d1ddf

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - pages/access.md
  - pages/links.md

font-size: small

include:
  - .well-known