[[redirects]]
from = "https://securitypuppy.netlify.com/*"
to = "https://securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.netlify.app/*"
to = "https://securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.securitypuppy.com/*"
to = "https://www.securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.com/security.txt"
to = "https://securitypuppy.com/.well-known/security.txt"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.com/privacy"
to = "https://securitypuppy.com/legal#privacy"
status = 302
force = true

[[redirects]]
from = "https://securitypuppy.com/contact"
to = "https://securitypuppy.com/about#contact"
status = 302
force = true

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy-Report-Only = "default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://securitypuppy.report-uri.com/r/d/csp/wizard"
Expect-CT = 'max-age=2592000, enforce, report-uri="https://securitypuppy.report-uri.com/r/d/ct/enforce"'
NEL = '{"report_to": "default", "max-age": 31536000, "include_subdomains": true}'
Referrer-Policy = "no-referrer"
Report-To = '{"group": "default", "max-age": 31536000, "endpoints": [{"url": "https://securitypuppy.report-uri.com/a/d/g"}], "include_subdomains": true}'
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-DNS-Prefetch-Control = "off"
X-Download-Options = "noopen"
X-Frame-Options = "DENY"
X-Permitted-Cross-Domain-Policies = "none"
X-Powered-By = "Coffee with puppies :)"
X-Security = "Puppies are awesome!"
X-XSS-Protection = "1; mode=block; report=https://securitypuppy.report-uri.com/r/d/xss/enforce"

[[headers]]
for = "/docs/*"
[headers.values]
X-Robots-Tag = "noindex, nofollow"

[[headers]]
for = "/.well-known/openpgpkey/hu/*"
[headers.values]
Content-Type = "application/octet-stream"
