[[redirects]]
from = "https://securitypuppy.netlify.com/*"
to = "https://securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.netlify.app/*"
to = "https://securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.securitypuppy.com/*"
to = "https://www.securitypuppy.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.com/security.txt"
to = "https://securitypuppy.com/.well-known/security.txt"
status = 301
force = true

[[redirects]]
from = "https://securitypuppy.com/resume"
to = "https://drive.google.com/file/d/1C_4shVuUIuAYcgN5oI6OXudvIWBYnfl0/view?usp=sharing"
status = 302
force = true

[[redirects]]
from = "https://securitypuppy.com/meeting"
to = "https://calendar.google.com/calendar/appointments/schedules/AcZssZ1uZJrp7nBNTD1GKeFbVhaPaVj0fOgKGXg9v17XEVKjfgKDCNY90SlHg55gbYXNsSwNwhHJRJ-_"
status = 302
force = true

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'none'; base-uri 'self'; child-src 'none'; connect-src milo.securitypuppy.com; font-src 'self' fonts.bunny.net; form-action 'none'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' milo.securitypuppy.com; manifest-src 'none'; media-src 'self'; object-src 'none';  prefetch-src 'none'; script-src 'self' milo.securitypuppy.com; style-src 'self' fonts.bunny.net; worker-src 'none'; report-uri https://securitypuppy.report-uri.com/r/d/csp/enforce; report-to default" 
Cross-Origin-Embedder-Policy = 'require-corp; report-to="default"'
Cross-Origin-Opener-Policy = 'same-origin; report-to="default"'
Cross-Origin-Resource-Policy = "same-origin"
Expect-CT = 'max-age=2592000, enforce, report-uri="https://securitypuppy.report-uri.com/r/d/ct/enforce"'
Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
NEL = '{"report_to": "default", "max-age": 31536000, "include_subdomains": true}'
Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
Referrer-Policy = "no-referrer"
Report-To = '{"group": "default", "max-age": 31536000, "endpoints": [{"url": "https://securitypuppy.report-uri.com/a/d/g"}], "include_subdomains": true}'
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-DNS-Prefetch-Control = "off"
X-Download-Options = "noopen"
X-Frame-Options = "DENY"
X-Permitted-Cross-Domain-Policies = "none"
X-Powered-By = "Coffee with puppies :)"
X-Security = "Puppies are awesome!"
X-XSS-Protection = "1; mode=block; report=https://securitypuppy.report-uri.com/r/d/xss/enforce"

[[headers]]
for = "/.well-known/openpgpkey/hu/*"
[headers.values]
Content-Type = "application/octet-stream"
