[[headers]]
for = "/*"
[headers.values]
Expect-CT= 'max-age=2592000, enforce, report-uri="https://securitypuppy.report-uri.com/r/d/ct/enforce"'
Referrer-Policy = "no-referrer"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Download-Options = "noopen"
X-Frame-Options = "DENY"
X-Permitted-Cross-Domain-Policies = "none"
X-Security = "Puppies are awesome!"
X-XSS-Protection = "1; mode=block; report=https://securitypuppy.report-uri.com/r/d/xss/enforce"